sinatra = Deck.create(name: "Sinatra")
javascript = Deck.create(name: "JavaScript")
activerecord = Deck.create(name: "ActiveRecord")
http = Deck.create(name: "HTTP")
cs_concepts = Deck.create(name: "CS Concepts")
agile = Deck.create(name: "Agile")

sinatra = Deck.find(1)
javascript = Deck.find(2)

sinatra.cards.create(question: "Is this a question?", answer: true)
sinatra.cards.create(question: "Is this a question(2)?", answer: true)
sinatra.cards.create(question: "Is this a question?", answer: true)
sinatra.cards.create(question: "Is this a question?", answer: true)
sinatra.cards.create(question: "Is this a question(2334)?", answer: true)
sinatra.cards.create(question: "Is this a question?", answer: true)
sinatra.cards.create(question: "Is this a question?", answer: true)
sinatra.cards.create(question: "Is this a question?(23234687)", answer: true)
sinatra.cards.create(question: "Is this a question?", answer: true)
sinatra.cards.create(question: "Is this a question?", answer: true)
