sinatra = Deck.create(name: "Sinatra")
javascript = Deck.create(name: "JavaScript")
activerecord = Deck.create(name: "ActiveRecord")
http = Deck.create(name: "HTTP")
cs_concepts = Deck.create(name: "CS Concepts")
agile = Deck.create(name: "Agile")
